const HEX_COLOR_PATTERN = /^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/;

function normalizeHexColor(value, fallback = null) {
  if (typeof value !== "string") return fallback;
  const trimmed = value.trim();
  if (!HEX_COLOR_PATTERN.test(trimmed)) return fallback;
  if (trimmed.length === 4) return `#${trimmed[1]}${trimmed[1]}${trimmed[2]}${trimmed[2]}${trimmed[3]}${trimmed[3]}`.toLowerCase();
  return trimmed.toLowerCase();
}

function normalizeCssUrl(value) {
  if (typeof value !== "string" || !value.trim()) return null;
  try {
    const url = new URL(value.trim());
    if (!["https:", "http:"].includes(url.protocol)) return null;
    return url.toString();
  } catch (error) {
    return null;
  }
}

function cssUrl(value) {
  const url = normalizeCssUrl(value);
  return url ? `url('${url.replace(/'/g, "%27")}')` : null;
}

function buildLogtoOrganizationBrandingCss(branding = {}) {
  const lightLogo = cssUrl(branding.lightLogoUrl || branding.logoUrl);
  const lightFavicon = cssUrl(branding.lightFaviconUrl || branding.faviconUrl);
  const lightColor = normalizeHexColor(branding.lightPrimaryColor || branding.primaryColor, "#0d6efd");
  const darkLogo = cssUrl(branding.darkLogoUrl);
  const darkFavicon = cssUrl(branding.darkFaviconUrl);
  const darkColor = normalizeHexColor(branding.darkPrimaryColor || branding.primaryColorDark, lightColor);

  const lines = [
    "/* Generated by Civitas from Logto organization customData.civitasProfile.branding. */",
    "#app * {",
    `  --civitas-brand-primary: ${lightColor};`,
    "}",
    "#app button[type='submit'] {",
    "  background: var(--civitas-brand-primary);",
    "  border-color: var(--civitas-brand-primary);",
    "}",
  ];

  if (lightLogo) lines.push("#app main[class*='main'] img[class*='logo'] {", `  content: ${lightLogo};`, "}");
  if (lightFavicon) lines.push("#app link[rel*='icon'] {", `  content: ${lightFavicon};`, "}");
  lines.push("@media (prefers-color-scheme: dark) {", "  #app * {", `    --civitas-brand-primary: ${darkColor};`, "  }");
  if (darkLogo) lines.push("  #app main[class*='main'] img[class*='logo'] {", `    content: ${darkLogo};`, "  }");
  if (darkFavicon) lines.push("  #app link[rel*='icon'] {", `    content: ${darkFavicon};`, "  }");
  lines.push("}");

  return {
    css: `${lines.join("\n")}\n`,
    normalized: { lightLogoUrl: normalizeCssUrl(branding.lightLogoUrl || branding.logoUrl), lightFaviconUrl: normalizeCssUrl(branding.lightFaviconUrl || branding.faviconUrl), lightPrimaryColor: lightColor, darkLogoUrl: normalizeCssUrl(branding.darkLogoUrl), darkFaviconUrl: normalizeCssUrl(branding.darkFaviconUrl), darkPrimaryColor: darkColor },
  };
}

module.exports = { buildLogtoOrganizationBrandingCss, normalizeCssUrl, normalizeHexColor };
